<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class DFYSitesContents extends CI_Controller
{

    function __construct()
    {
        parent::__construct();
        $this->load->helper('jwt_helper');
    }

    public function index()
    {
        $articles = array(
            array(
                'article_id' => '99999999901',
                'article_name' => 'The Best Digital Marketing Strategies This Year',
                'article_content' => "<p>The Best Digital Marketing Strategies This Year</p><p>&nbsp;</p><p>Entrepreneurs and businesses are now shifting to the online realm to sell. They are now keen to find creative ways to build their audience and convert them to paying clients.</p><p>&nbsp;</p><p>Below are the best digital marketing strategies that you can use in your business.</p><p>&nbsp;</p><p>Email Marketing</p><p>This strategy has the highest return of investment at $38 per every dollar spent. The volume of the emails were surprisingly high last year and has continued growing ever since. This strategy has the highest conversion rates among the other digital marketing techniques. Start building your list now and make your products and services known to your target clients.</p><p>&nbsp;</p><p>Affiliate Marketing</p><p>This type of marketing increases brand awareness and encourages business growth. Customers are going to buy your products and services because other people are going to advertise them for you, in exchange for a commission fee. This is one of the best techniques with the lowest budget and not much effort but will give you a high return of investment.</p><p>&nbsp;</p><p><strong>Social Media Marketing</strong></p><p>In this strategy, you are utilizing the power of social media in promoting your product. You can hire influencers to advertise your offers and make your brand known to their followers. You can also buy ads from Facebook, Instagram, and Youtube to improve your social media presence.</p><p>&nbsp;</p><p><strong>SEO Marketing</strong></p><p>Every business wants to appear on the first page of Google. Search engine optimization works through the use of keywords, backlinking, guest posting, and optimizing your content based on Google&rsquo;s algorithm. This is one of the most effective tool to improve and strengthen your brand image.</p><p>&nbsp;</p><p>You can use all these strategies at the same time for maximum returns. Consider your budget, expertise, goals, and target audience before you start any of these marketing strategy to make the most of your efforts and funds.</p>",
                'category' => "biz_op",
                'category_id' => 1
            ),
            array(
                'article_id' => '99999999902',
                'article_name' => 'Top Problems That Digital Entrepreneurs Face',
                'article_content' => "<p>Top Problems That Digital Entrepreneurs Face</p><p>&nbsp;</p><p>Entrepreneurship has undoubtedly become more competitive these days. Small business owners are trying their luck to become the next viral business. Marketing strategies are growing and advertising tactics are becoming competitive as well. The sudden shift of most entrepreneurs and customers to the online realm has also added to the challenge.</p><p>&nbsp;</p><p>Too Much Competition</p><p>If you want a profitable business, then prepare for lots of competition. Everyone wants a product or service that would give them the highest return of investment. The problems that digital entrepreneurs face is not really the fact of competition, but the fact that their offers do not stand out in the market.</p><p>&nbsp;</p><p>Security Issues</p><p>There are always security concerns in the cyberworld. Small businesses are usually the target of these cyber security threats. Even attackers have already automated their plans so it is now easier for them to target customers and business owners alike. Don&rsquo;t take for granted the web security solutions and application to protect you from these concerns.</p><p>&nbsp;</p><p>Lack Of Marketing Strategy</p><p>Poor marketing strategy has been one of the most common reasons why half of start up businesses fail nowadays. Customers won&rsquo;t come to your online store automatically once you put up a business. You have to make them realize that they need your products or services. Effective advertising strategies depend on who your target audience are.</p>",
                'category' => "biz_op",
                'category_id' => 1
            ),
            array(
                'article_id' => '99999999903',
                'article_name' => 'The Major Differences Between A Partnership And A Corporation',
                'article_content' => "<p>The Major Differences Between A Partnership And A Corporation</p><p>Not all business models are the same. A group of business-minded people often brainstorms about the type of business that they would enter into. Partnerships and corporations are the most common. Here are the differences between the two:</p><p>&nbsp;</p><p>Composition</p><p>A partnership is composed of partners, while a corporation has shareholders. In both cases, the people who compose these business models share in the expenses and profits of the business. They mainly differ on the management duties and liabilities. Partners generally have equal shares in the losses and profits of the business. Meanwhile, the profits by the corporate shareholders depend on how much they share in the capital of the business.</p><p>&nbsp;</p><p><strong>Liability</strong></p><p>A corporation is an entity separate from its shareholders. The assets of the corporation would be the ones to pay for the company&rsquo;s debts. Creditors cannot run after the personal assets of the shareholders. In a partnership, the partners are personally liable for the debts of the venture. Partners are always at risk once the business fails or incurs any damages.</p><p>&nbsp;</p><p>Management</p><p>Partners are usually in charge of the daily operations in the partnership. The more partners there are, the more people share the responsibility of carrying out the management operations. Corporate shareholders, on the other hand, elect board members who will oversee the operations of the business.</p><p>&nbsp;</p><p>Taxation</p><p>Business partnerships technically don&rsquo;t have taxes. Instead, individual partners are taxed based on their income from the partnership. Corporations have complex tax obligations. Dividends and profits are taxed by the state where it is formed.</p><p>&nbsp;</p><p>Corporations have a much formal structure that is governed by the laws of the country where they are formed. Partnerships have a complex structure because some partners are merely investors in the venture, hence, they don&rsquo;t really share in the management duties of the business. Weigh in your long-term goals before you start either of these two.</p>",
                'category' => "biz_op",
                'category_id' => 1
            ),
            array(
                'article_id' => '99999999904',
                'article_name' => 'Operational Issues That Every Boss Should Hear About',
                'article_content' => "<p>Operational Issues That Every Boss Should Hear About</p><p>Day-to-day issues in a business is something that cannot be avoided. Entrepreneurs, especially start-up businesses, should be wary of what the most common problems are so they can plan everything out before they do more damage to the company.</p><p>&nbsp;</p><p>High Overhead Costs</p><p>&nbsp;</p><p>Overhead costs that are out of control can deplete a business&rsquo;s capital sooner. Assess your company&rsquo;s industry, profitability, and size first so you can budget your daily expenses. Cut out expenses that are not really doing good to the company.</p><p>&nbsp;</p><p>Lack Of Performance Monitoring</p><p>Set KPIs so your employees will work efficiently. Plan your marketing and financial goals and make them known to your whole team. An employee may be at a loss to what his job responsibility really is, so make sure that you, as a boss, will continue to monitor his progress and commend him for a job well done.</p><p>&nbsp;</p><p>Cyber Security Concerns</p><p>A random attack can put your investments to waste. Every business is vulnerable to these automated attacks. It&rsquo;s okay to spend a little on systems and softwares that will protect you from these security threats. Imagine how much you would lose at only one hacking incident that could happen anytime.</p><p>&nbsp;</p><p>No Proper Mindset</p><p>Having only short-term goals is not sustainable. A boss should always seek long-term goals to stay motivated even when problems arise. Most of the time, long-term goals are compressed as short-term ones so every employee is pressured. Take it one step at a time. Have a business plan and don&rsquo;t make everything look hurried.</p><p>&nbsp;</p><p>It&rsquo;s better to spot these problems earlier. These issues will not fix by themselves. A good boss knows how to deal with these issues at the earliest possible time to avoid further detriment to the business, especially on the financial aspect of the venture.</p>",
                'category' => "biz_op",
                'category_id' => 1
            ),
            array(
                'article_id' => '99999999905',
                'article_name' => 'What To Do If You&rsquo;re On The Verge Of Bankruptcy',
                'article_content' => "<p>What To Do If You&rsquo;re On The Verge Of Bankruptcy</p><p>&nbsp;</p><p>Every business has a risk of failing. Half of startup businesses fail because of problems like lack of sufficient capital, poor marketing strategy, and lack of customers. However, there are still available options to save a failing business. Below are some of the best steps you should consider.</p><p>&nbsp;</p><p>Reconsider Your Expenses</p><p>Overhead costs can sometimes become out of control. Don&rsquo;t splurge much to make your office look very aesthetic when you already know that your finances could not afford any more of it. You can sell equipment that is not really helping the business. Know the wants and needs of the company, too. Maybe you can cut down marketing strategies that are not working and streamline your daily operations.</p><p>&nbsp;</p><p>Plan For The Worst</p><p>Don&rsquo;t take business plans for granted. This will be your cheat sheet when something wrong occurs in the business. A good plan outlines the necessary steps once your company encounters problems. Make sure that you have other capital resources to help you recover.</p><p>&nbsp;</p><p>Bring More Effort Towards Customer Satisfaction</p><p>Customers can save your business. If your budget can still market your product at a low cost, then go for it. Make your brand more visible through means available online. It can generate you more cash flows and eventually save your business from bankruptcy.</p><p>&nbsp;</p><p>Check Your Insolvency Laws</p><p>Every country provides help for businesses that are at the risk of shutting down. Companies which have good credit standing and which used to earn well are given priority by these insolvency laws. The State will help you to postpone payment for your debts until you&rsquo;re back on track again.</p><p>&nbsp;</p><p>Don&rsquo;t lose hope if your business semms to be failing at the start. Remember that big brands today have once experienced distress due to a lot of factors but they&rsquo;ve managed to recover and get back on track. Your business plans should also plan out times like this so you will always be prepared for the worst.</p>",
                'category' => "biz_op",
                'category_id' => 1
            ),
            array(
                'article_id' => '99999999906',
                'article_name' => 'The Importance of Research In Business',
                'article_content' => "<p>The Importance of Research In Business</p><p>&nbsp;</p><p>Business leaders should still see to it that the company value research and development. In fact, the need for researchers and surveyors in a business are increasing these days. The needs of the mordern world have become&nbsp; more complicated.&nbsp; Here are the benefits that you can get from research:</p><p>&nbsp;</p><p>To Find More Opportunities</p><p>The trend of startup businesses today is to find a product, repurpose it then sell it online. You&rsquo;ll be amazed at how creative these minds are that they can earn profits at a simple thing just by looking at it from a new perspective. As an example, a simple brush holder is now being marketed as a highlighter organizer. It&rsquo;s now getting more popular to students aside from makeup artists and business enthusiasts.</p><p>&nbsp;</p><p>To Plan For Possible Problems</p><p>A research will uncover possible situations that can lead to big problems. Business leaders know how a simple complaint that goes viral on social media can lead to big financial losses. Undertaking research can aid the company find what&rsquo;s not to advertise as it could harm some cultures. The world is changing and any single move of a business could harm the operations immediately.</p><p>&nbsp;</p><p>To Identify The Best Marketing Strategy</p><p>Research is important to help identify who your target audience are. Analysis of the segments in your target will bring the best marketing strategy that can earn you big profits. A simple survey with well-crafted questionnaires can uncover problems of your target consumers that could be remedied by your products or services. That is a very good marketing content. Most people do not realize that they need your product unless it is properly communicated with them.</p><p>&nbsp;</p><p>You don&rsquo;t have to hire an expensive research company to do these analyses. If you are a startup business, you can do all of these during your free time. Freelance market researchers can also help you perform in-depth market analysis at a low cost!</p>",
                'category' => "biz_op",
                'category_id' => 1
            ),
            array(
                'article_id' => '99999999907',
                'article_name' => 'Should I Hire Freelancers In My Small Business Instead?',
                'article_content' => "<p>Should I Hire Freelancers In My Small Business Instead?</p><p>&nbsp;</p><p>Freelancing is slowly becoming a trend today. Professionals, students, out-of-school-youth, and even retirees have started their freelancing career at home. Major brands and companies are also starting to realize the significance of the freelancers to their businesses.</p><p>&nbsp;</p><p>Freelancer Can Make The Business Operations More Efficient</p><p>Freelancers do their freelancing activities at home. They are not pressured to commute everyday to work and to report at a particular time physically. They are more efficient and more productive at this setup. Freelancers are also usually paid by output so you are assured that they can produce the highest quality of work.</p><p>&nbsp;</p><p>Freelancers Are The Most Specialized In Their Respective Fields</p><p>More often than not, a freelancer already has vast experience from different companies before they land a job with you. They have the best skill when it comes to, say, marketing your product online. You can say that they are already an expert because these practical applications had already honed their skills even without proper training from the start.</p><p>&nbsp;</p><p>Hiring Freelancers Cut Costs In The Long Run</p><p>Since freelancers work from home, you can save costs in terms of internet access and computer equipment. You won&rsquo;t have to pay for the freelancers&rsquo; travel and food allowances, too. On the part of the freelancer, they also save costs in terms of housing and transportation allowances. These expenses won&rsquo;t cut their salaries anymore.</p><p>&nbsp;</p><p>You Have More Options</p><p>Freelancing activity is worldwide. You&rsquo;d only need an internet connection to connect with freelancers around the world. You can reach even those from far-away places who are best suited to your company&rsquo;s needs.</p><p>&nbsp;</p><p>Startup companies are the ones usually hiring freelancers. It saved a lot of expenses and the output of work is at par with hiring in-house teams or agencies. There are a lot of outsourcing online sites where you can find your first freelancer to work with.</p>",
                'category' => "biz_op",
                'category_id' => 1
            ),
            array(
                'article_id' => '99999999908',
                'article_name' => 'Why Stress Management Is Important',
                'article_content' => "<h1><strong>Why Stress Management Is Important</strong></h1><p>&nbsp;</p><p>When you are stressed, the first thing that happens is the lack of brain coordination. Stress can trigger negative thoughts, and at the same time, one&rsquo;s ability to multitask is diminished.Stress management consists of a wide range of techniques and tools to help you decrease your stress levels and improve your ability to respond to them.</p><p>&nbsp;</p><p>Managing stress is important because of the following:</p><h1>To Think Clearly</h1><p>When you are stressed, the mind cannot process things clearly. With proper stress management, our brain can take a short break in order to refresh. Think of it as a compputer lagging behind. A restart would usually fix all the lagging functions and it&rsquo;ll continue to work like a newly-bought machine.</p><h1>To Function Efficiently</h1><p>Our brains are not robots that can function 24 hours a day. If you do not manage your stress, your physical and mental well-being would be negatively affected which would oftentimes result in errors and mistakes on the tasks at hand.</p><h1>For Proper Sleep</h1><p>Lack of proper sleep is linked to prolonged stress levels. Lack of quality sleep results to decreased memory skills and a poor mood / emotion regulation. Your workplace productivity is impaired as well if you cannot manage your stress level properly.</p><h1>For Better Mental Health</h1><p>Anxiety and depression often start because of stress and pressure. If a person is taking a break once in a while, he surely can think clearly and process these emotions with clarity. A visibly stressed person would exhibit poor decision skills. He would also have a hard time putting things into perspective.</p><h1>Final Thoughts</h1><p>Stress management will only require a little bit of your time and willingness to do so. The internet can offer you a lot of practices and tips on how to properly manage your stress levels. The best part is that most of them are only for free.</p>",
                'category' => "health_fitness",
                'category_id' => 2
            ),
            array(
                'article_id' => '99999999909',
                'article_name' => 'Tips On Achieving A Healthy Lifestyle With Your Family',
                'article_content' => "<h1><strong>Tips On Achieving A Healthy Lifestyle With Your Family</strong></h1><p>&nbsp;</p><p>&nbsp;</p><p>Parents should always be the best example in teaching their kids how to live the proper and healthy lifestyle. The neatness and proper organization of a home should be a goal of every family. It is the parents&rsquo; responsibility to their kids on how to achieve this even in the smallest possible ways.</p><p>&nbsp;</p><p>A healthy lifestyle does not always involve eating fruits and vegetables. It&rsquo;s just one of the many ways to do so. Below are some of the helpful tips on how to live a healthy lifestyle.</p><h1>Train Your Kids To Eat Fruits</h1><p>&nbsp;</p><p>Parents can do this by stocking up on healthy alternatives too. Instead of filling your pantry with junk food and chips, make it a habit to fill your fridge with fresh fruits and vegetables too. So that when your kids are feeling hungry, they would get used to eating healthy food instead of pure unhealthy snacks.</p><h1>Do Basic Workouts Together</h1><p>&nbsp;</p><p>Schedule physical workouts at least once a week with the whole family. You don&rsquo;t have to enroll in workout classes and force your kids to train with you. You can do it by jogging together around the neighborhood every early Saturday morning. Or maybe, bike together in a park to breathe some fresh air.</p><h1>Keep Your Home Organized</h1><p>&nbsp;</p><p>An untidy home can invite stress in your house. Schedule a general cleaning with the kids once in a while, too. Teach them to let go of the things that they don&rsquo;t really use. Give your kids responsibility such as taking the trash out at a certain time of the day. This habit will also help them in the future when they have their own homes.</p><h1>Final Thoughts</h1><p>These are just some of the manageable ways to start a healthy lifestyle with your family. The wellbeing of the family members are dependent on the parents as the kids&rsquo; best examples. Soon, your home and your family will get used on living this healthy lifestyle!</p>",
                'category' => "health_fitness",
                'category_id' => 2
            ),
            array(
                'article_id' => '99999999910',
                'article_name' => 'Stay Fit To Be Successful',
                'article_content' => "<h1><strong>Stay Fit To Be Successful</strong></h1><p>&nbsp;</p><p>Successful people who generate higher income and sales from their respective businesses never take their health for granted. For them, staying fit and eating healthy are one of the reasons why they are on top. However, it does not mean that they workout or go to the gym every single day.</p><p>&nbsp;</p><p>Here are their tips in staying fit even while they are busy at their endeavors:</p><h1>Be Consistent In Your Workouts</h1><p>&nbsp;</p><p>Successful people usually jogs around the neighborhood regularly. The keyword here is consistency. You don&rsquo;t have to perform strenuous activity each day before working. As long as you can get yourself moving at least once a wekk and stick with it, then the benefits of staying fit will last for long.</p><h1>A Little Cardio Will Do</h1><p>&nbsp;</p><p>Even busy people squeeze in at least 15 minutes of jogging or walking every morning. It&rsquo;s a simple activity of their choice that does wonders to their physical and mental well-being. A little cardio can boost endorphin production, or that chemical responsible for &ldquo;good&rdquo; feelings.</p><h1>Know What A Balanced Diet Is</h1><p>&nbsp;</p><p>A balanced diet is a meal complete with the proper nutrients our body needs. If you think you lack particular vitamins from your everyday food, take supplements or talk to a health professional so you&rsquo;ll know the proper dosage of these vitamins.</p><h1>Take Breaks Once In A While</h1><p>&nbsp;</p><p>Taking breaks is something that one should not take for granted. It is the best stress management tool that can benefit both the mind and the body. Did you know that you have a higher chance of eating unhealthy food if you are sleep deprived? Lack of quality breaks create a negative domino effect on the mind and body.</p>",
                'category' => "health_fitness",
                'category_id' => 2
            ),
            array(
                'article_id' => '99999999911',
                'article_name' => 'Importance of Skin Care Routines',
                'article_content' => "<h1><strong>Importance of Skin Care Routines</strong></h1><p>&nbsp;</p><p>DNA genetics are not the only reason why a person has healthy and clear skin. Don&rsquo;t blame that you have bad genetics if your skin is not as healthy as others have. It also depends on your lifestyle and your choice of skin products. Develop proper habits and stick to it to achieve a younger-looking and a well-nourished face and body.</p><p>&nbsp;</p><p>Consider the following benefits of developing your own skin care routine:</p><h1>Skin Cells Die And Shed Regularly</h1><p>If you don&rsquo;t establish a healthy skin care routine, your new cells will just look tired and dull everyday. Just because you applied a moisturizer today, it does not mean that you will have supple skin the day after. Make it constant and see how refreshed and glowing your skin will look everyday.</p><h1>Glowing Skin Can Boost Self-Confidence</h1><p>Acne scars, premature skin aging, and discolorations can be prevented by regular skin care routine! Our skin cells change regularly so proper care should be practiced every time old cells are shed off.</p><p>&nbsp;</p><p>Personal appearance always matters, especially at the first meeting with your date, or your boss. If you have clear and glowing skin thanks to proper and regular skin routine, you&rsquo;ll have more confidence to chin-up and walk without hiding your face. Pimples can be minimized even if you have acne-prone skin. Regular skin routine can do the trick.</p><h1>Healthy Routine Can Save Money</h1><p>Skin aging and pimple scars can be prevented early. Sunscreen and sunflower oil are the best when it comes to this. Dermatologists and skin surgeries just to remove these &lsquo;imperfections&rsquo; can be costly. You&rsquo;ll thank yourself in the future so it&rsquo;s better to start now.</p><h1>It Can Teach You How To Live A Healthy Lifestyle, Too</h1><p>A healthy skincare routine also involves healthy food choices. Now that you have an established skincare habit, you&rsquo;ll want to fix your eating habits too so your skin will look even more glowing and younger.</p><p>&nbsp;</p><h1>Final Thoughts</h1><p>Getting that clear skin you always see on celebrities and commercials entails commitment. There are really no shortcuts because even clear skin which has undergone medical procedures requires constant maintenance. Start your healthy routine today and see the difference in the coming weeks!</p>",
                'category' => "health_fitness",
                'category_id' => 2
            ),
            array(
                'article_id' => '99999999912',
                'article_name' => 'How To Fix Your Sleep Routines',
                'article_content' => "<h1><strong>How To Fix Your Sleep Routines</strong></h1><p>&nbsp;</p><p>A disrupted sleep can give you an entire day of mood swings the following day. A proper sleep schedule can fix this. You&rsquo;ll wake up more refreshed if you have a constant sleep schedule and you know exactly what time you should wake up, even if your alarm clock fails to ring in the morning.</p><p>&nbsp;</p><p>These are the best tips to follow to fix your sleep routine.</p><h1>Lights Out</h1><p>Make it a habit to turn off the TV and dim your phone and other gadgets when you go to bed. A notification light can distract you from dozing off. If the street lights are coming into your room, curtain blinds would be helpful.</p><h1>Avoid Caffeine At Least 3 Hours Before Bed</h1><p>The effects of coffee stay the whole day. Avoid drinking any drink with caffeine after 6:00 PM. Drink caffeine-free teas instead such as lavender or chamomile teas. They also aid in proper relaxation because of their healing properties.</p><h1>Do Some Light Workout</h1><p>Get moving before you go to bed. Do some yoga or a little bit of stretching. This will make you fall asleep easily. 30 minutes of cardio (such as walking, jogging, running) can also provide you quality sleep at night.</p><h1>Check Your Environment</h1><p>Make sure that your room temperature is just right, not too hot and not too cold. Check if your bed is comfortable enough for the whole night. You can also wear earplugs if there are noises that you cannot get rid of (such as construction works or the city traffic noises outside). Change your mattresses and pillows if they are already old enough and brings you pains and muscle fatigue instead of comfort.</p><p>One night of full sleep in a comfortable environment will bring you instantaneous effects the following day. If you do these habits regularly, the significant benefits will stay with you in the long run. You&rsquo;ll get used to this healthy sleeping routine after a week of sticking with these habits so better start now!</p>",
                'category' => "health_fitness",
                'category_id' => 2
            ),
            array(
                'article_id' => '99999999913',
                'article_name' => 'Healthy Weekend Activities For Your Mind And Body',
                'article_content' => "<h1><strong>Healthy Weekend Activities For Your Mind And Body</strong></h1><p>&nbsp;</p><p>Our days have undoubtedly become much more stressful nowadays. The pile of work is now literally beside our bed since the work-from-home policies have been implemented due to the pandemic. Even our weekends are now devoted to work because the line between working hours and resting time has now become blurry.</p><p>&nbsp;</p><p>It&rsquo;s not healthy to not take a break every now and then. Our brains are not created to function 24/7. It&rsquo;s still important that we have recreational activities even in the time of the pandemic. Here are some of the best and healthy activities that you can try this weekend:</p><h1>Exercise</h1><p>Go for a walk to release endorphins. It will help in regulating your emotions and mood instantly. Breathe some fresh air and you&rsquo;ll see things in a new perspective.</p><p>&nbsp;</p><p>Your joints usually get stuck after a day of sitting and typing at your desk. It&rsquo;s very unhealthy and can cause physical complications in the future. By exercise, it does not mean you have to enroll in yoga classes or sign up for gym membership. That can be costly. A 15-minute walk will do just fine.</p><h1>Create Motivational Art</h1><p>Daily positive affirmations are proven by Science as an effective motivational and stress management tool. Add the fact that these encouraging quotes are always shown on colorful canvas, be it digital or print. If you are someone who loves doing calligraphy and creating digital art, then maybe you can create artworks with motivational words written on it.</p><h1>Play Sports</h1><p>You can invite your family to play some backyard sports during your free time. Playing at least one sport can awaken your skills and make you even more competitive. This can aid in your productivity at work or at school.</p><h1>Organize Your Home</h1><p>Declutter your workspace and bedroom. It&rsquo;s fun when you uncover stuff from a long-time ago and reminisce about all the memories that come with it. You might also find some things that you don&rsquo;t use anymore and perhaps, make money from them by selling them online. Redecorate your room as well if you feel like your room is getting a bit dull. Colorful spaces can boost productivity.</p><p>&nbsp;</p><p>The best thing about these activities is that they are for free! Pre-pandemic, weekend activities usually mean a night out or an expensive getaway. Take your mind off work this weekend and try some of these activities.</p>",
                'category' => "health_fitness",
                'category_id' => 2
            ),
            array(
                'article_id' => '99999999914',
                'article_name' => 'Best Vitamins For A Metabolism Boost',
                'article_content' => "<h1><strong>Best Vitamins For A Metabolism Boost</strong></h1><p>&nbsp;</p><p>Metabolism is that chemical process which includes the breaking down of nutrients from food to help our body function well. For fitness junkies, most especially people who want to lose weight, a fast metabolism is a must to burn extra calories from the food they consume.</p><p>&nbsp;</p><p>A fast metabolism is a product of many factors. Other than physical movement, the food we eat and the vitamins we take play a huge part in this. Here&rsquo;s a quick rundown of the best vitamins to give your metabolism a boost.</p><h1>B Vitamins</h1><p>B-complex vitamins are in charge of metabolizing or breaking down proteins, carbs, and fats&nbsp; into energy. Without these, they will be stored as fats. Good sources of B vitamins are seafood, lean meats, eggs, dairy products, nuts, apples, bananas, and grapes.</p><h1>Iron</h1><p>This chemical makes our cells and hormones function correctly. Iron is responsible for sending oxygen to the muscles. Muscle groups that do not receive enough oxygen won&rsquo;t burn fat. However, high doses of iron can be lethal.</p><p>&nbsp;</p><p>Good sources of iron are the following: nuts, tofu, brown rice, and leafy vegetables.</p><h1>Magnesium</h1><p>Low levels of magnesium can cause bad headaches and will make you more nervous. People with magnesium deficiency also have slower metabolism which can cause them to store more fat. They would usually feel weak and physically numb. Foods such as nuts and leafy vegetables are high in Magnesium.</p><h1>Vitamin D</h1><p>One study related to this vitamin shows that people with higher stored fat have lower vitamin D as compared to those who have lesser body fats. It has also been suggested that Vitamin D plays a huge part in controlling one&rsquo;s blood sugar. You can get your daily dose of this chemical from sun exposure and from consuming foods like egg yolks, fish, beef liver, and cereals.</p><h1>Final Thoughts</h1><p>These supplements can aid in boosting one&rsquo;s metabolism. Caffeine and green tea are also shown to help as well. However, if your main goal is to shed some pounds, a major change in lifestyle and diet is the most effective way to reach this goal. If you are planning to consume pills and vitamin supplements, it is also best to consult a doctor first for the proper dosage.</p>",
                'category' => "health_fitness",
                'category_id' => 2
            ),
            array(
                'article_id' => '99999999915',
                'article_name' => 'The Formula To Self-Confidence',
                'article_content' => "<p>The Formula To Self-Confidence</p><p>&nbsp;</p><p>Having self-confidence means having to trust yourself in terms of your abilities, judgement, and other qualities. It does not necessarily mean that you are an expert on a certain thing but it means that you trust your skills enough to take on a challenge and take control.</p><p>&nbsp;</p><p>Self-confidence cannot be taught fully in school. It is a product of experiences from childhood until the present. The following are the main factors that contribute heavily to the development of self-confidence, be it for you or for your kids.</p><p>&nbsp;</p><p>Good Childhood Memories</p><p>Parents who are very critical of their kids impact the latter&rsquo;s self-esteem negatively as they grow up. These kids grow up very conscious about their looks and achievements in life. Another factor is the environment that the child grew up in. Unstable households are linked to low self-confidence. Family problems that arise from these households are also the same burden that the children would carry until they grow up.</p><p>&nbsp;</p><p>Self-love Practices</p><p>The media, nowadays, have a very huge impact on one&rsquo;s self-confidence and self-esteem. A person&rsquo;s routine on taking care of himself physically, mentally, and emotionally can say a lot about his self-confidence. Parents should teach their kids the proper use of social media. Comparison is never healthy if it can destroy your standards of beauty and make you hate yourself.</p><p>&nbsp;</p><p>Supportive Family And Friends</p><p>A person&rsquo;s relationship with family and friends can also affect self-confidence. Some people can destroy your self-esteem anytime so it&rsquo;s better to surround yourself with positive people who will support you in all endeavors. Good family and friends won&rsquo;t make you feel like you are incomplete or lacking certain life skills.</p><p>&nbsp;</p><p>Final thoughts</p><p>These factors are major contributors to the development of your self-confidence. You still have control over your life and your self-esteem. Even if these factors (especially if you have&nbsp; childhood and unsupportive family members) are not doing any good on your confidence nowadays, you can always set them aside and focus on yourself instead.</p>",
                'category' => "personal_development",
                'category_id' => 3
            ),
            array(
                'article_id' => '99999999916',
                'article_name' => 'Easy De-Stressing Activities That You Can Do Regularly',
                'article_content' => "<h1>Easy De-Stressing Activities That You Can Do Regularly</h1><p>&nbsp;</p><p>Stress-relief activities do not always mean expensive travels and staycations to tourist destinations. It can always be as simple as the following:</p><h1>A Quick Yoga / Exercise</h1><p>A light exercise or an online yoga is usually the best stress-relief activity in the comforts of your home. It will also do good on your physique after a long day of sitting down at work. It can instantly regulate your mood and help you have a quality sleep at night.</p><h1>Journaling</h1><p>Take down your thoughts and confess your roadblocks for today. Adulthood does not mean you have to let go of designing your own diary during your free time. Keep in track of your mood and emotions day by day so you&rsquo;ll easily identify your stress and anxiety triggers.</p><h1>Answer Crossword Puzzles</h1><p>It is believed that when stressed, our brain keeps on looking for a problem that it needs to solve. If you are suffering from a mental stress, grab a simple crossword puzzle online and work on it. Besides, it feels good to have that &ldquo;accomplished&rdquo; feeling before you go to bed.</p><h1>Dance</h1><p>People dance to release stress and emotions. Like any other cardio, it burns fat and releases endorphins to make you feel good right after. If your body feels calm, then your mind follows. Moreover, it is a creative outlet to show your personality without judgment from other people. You can dance all night in your room and no one will judge you. It&rsquo;s your safe haven from this harsh world!</p><h1>Stress Bake</h1><p>Stressed people are fond of accomplishing things even while they are stressed. Baking is a good form of relief because your mind is distracted with all the baking procedures. The resulting baked goods can also provide you a sense of accomplishment. Try this baking therapy now with the hundreds of free easy recipes online!</p><h1>Final Thoughts</h1><p>You don&rsquo;t have to open your wallet and spend a fortune on these stress relief activities! Let&rsquo;s accept the fact that stress is already part of our daily life but it&rsquo;s up to us if would let it affect our well-being in the long run.</p>",
                'category' => "personal_development",
                'category_id' => 3
            ),
            array(
                'article_id' => '99999999917',
                'article_name' => 'How Effective Is The Pomodoro Technique',
                'article_content' => "<p>How Effective Is The Pomodoro Technique?</p><p>&nbsp;</p><p>Who would have thought that a tomato kitchen timer can teach a person how to properly manage his time and get things done before the end of the day? The Pomodoro technique really does wonders to students, employees, and even to the bosses.</p><h1>What Is This Technique?</h1><p>&nbsp;</p><p>Pomodoro Technique was developed in 1980s by Francesco Cirillo. He used a small tomato kitchen timer which he set to 25 minutes in length and another 5 minutes for a short break. The whole round of 25 and 5 minutes is called the pomodoro interval.</p><p>&nbsp;</p><p>Basically, you get a task done within 25 minutes and take a short break of 5 minutes. After every 4 or 5 pomodoro intervals, you can get a longer break of 10 minutes or so.</p><h1>Is It Really Effective?</h1><p>&nbsp;</p><p>Science says it is indeed effective in boosting one&rsquo;s productivity.</p><p>&nbsp;</p><p>The forced breaks between the tasks are said to minimize the feeling of exhaustion as you continue working on your tasks. It minimizes error and discrepancies in your work, which makes every task at hand more polished as a result. You will also keep track of the small details that you might miss out because your day needs to start with a plan. The first step in the Pomodoro technique would be you choosing a task to finish within the first 25 minutes.</p><p>&nbsp;</p><p>At the end of the day, you will feel more accomplished to see your checklist full of checkmarks.</p><h1>Final Thoughts</h1><p>&nbsp;</p><p>The best thing about this method is that it is entirely free! You may buy a little kitchen timer but you can also use the free apps on your phone. You can now avoid missed deadlines, inefficient work, and procrastination tendencies thanks to the Pomodoro technique.</p>",
                'category' => "personal_development",
                'category_id' => 3
            ),
            array(
                'article_id' => '99999999918',
                'article_name' => 'How To Practice Leadership At Home',
                'article_content' => "<p>How To Practice Leadership At Home</p><p>&nbsp;</p><p>&nbsp;</p><p>Even with the lockdowns and restrictions on going out the house, you can still hone your leadership skills in the comforts of your house. Parents can also learn about these tricks to teach to their kids.</p><p>&nbsp;</p><p>Practice Good Discipline</p><p>Leaders know how to assess which one is right and which one is wrong. You can start by asking yourself to eat a proper balanced diet and avoid junk foods regularly. Someone with good eating discipline knows it&rsquo;s also okay to indulge in these sweets and &ldquo;sin&rdquo; foods only at appropriate times.</p><p>&nbsp;</p><p>Don&rsquo;t Be Afraid Of Responsibilities</p><p>Take charge of some house responsibilities and be accountable. A parent should teach their kids how to stick with these responsibilities such as taking the trash out in the evening, avoiding fights with siblings, and cleaning their rooms everyday.</p><p>&nbsp;</p><p>Develop Communication Skills</p><p>A true leader knows how to communicate with his team members. He knows that certain acts can affect someone emotionally and mentally. If you or your kids know the proper way to talk and listen, then chances are high that you&rsquo;d build more quality relationships with your team members in the future.</p><p>&nbsp;</p><p>Practice Organization Skills</p><p>Your mind cannot think well if your space is cluttered. A parent should educate their kids how to keep their personal space neat and organized. Keep a journal to track your times and tasks at hand, too.</p><p>&nbsp;</p><p>Final Thoughts</p><p>&nbsp;</p><p>Leadership skills are important because you don&rsquo;t let others dictate which path to take on and how to accomplish one thing. Start honing your skills now and say hello to a better journey to success.</p><p>&nbsp;</p>",
                'category' => "personal_development",
                'category_id' => 3
            ),
            array(
                'article_id' => '99999999919',
                'article_name' => 'How To Stay Productive Even If You Woke Up Late_',
                'article_content' => "<p>How To Stay Productive Even If You Woke Up Late?</p><p>&nbsp;</p><p>It&rsquo;s hard to stay motivated and in high energy all day if you have loads of paperwork in front of you from 8 AM until 5 PM. Add the fact the stressful news about politics and economy that you keep hearing on TV and on social media.</p><p>&nbsp;</p><p>Here are our hacks to stay productive all day.</p><p>&nbsp;</p><p>Plan Your Tasklist</p><p>Never miss any small important details again with your beautiful journal. Every night before you go to bed, list down all the tasks that you want to accomplish the following day. Stick with this schedule and wake up according to the plan. By the end of the day, it feels good to check all the tasks boxes that you achieved today.</p><p>&nbsp;</p><p>Remember to Set Deadlines</p><p>Every task should come to an end. Workload seems endless because most of the time, people do not put deadlines on their tasks. This hack will also get rid of your procrastination tendencies. Your breaks will also be regulated because you are running on a deadline.</p><p>&nbsp;</p><p>Play Soothing Music</p><p>Science shows that classical music helps in the concentration and focus of an individual. If you are in a work-from-home setup, try this trick so your spirits will be uplifted and your work will get finished in time.</p><p>&nbsp;</p><p>Do Light Cardio</p><p>Light physical movements will help you sleep like a baby. 10 mins of brisk walking or one online yoga session will do. Quality sleep will then aid in your productivity the next day.</p><p>&nbsp;</p><p>Final Thoughts</p><p>&nbsp;</p><p>You only need the right mindset and the right habits to start boosting your productivity. These hacks can produce instantaneous effects so better try them now!</p><p>&nbsp;</p>",
                'category' => "personal_development",
                'category_id' => 3
            ),
            array(
                'article_id' => '99999999920',
                'article_name' => 'Minimize Negative Thoughts By These Simple Practices',
                'article_content' => "<p>Minimize Negative Thoughts By These Simple Practices</p><p>&nbsp;</p><p>A person is said to have at least 70,000 thoughts everyday. Negative thoughts share a part of this number, and, most of the time, it can outnumber the positive thoughts in our mind.</p><p>&nbsp;</p><p>Common negative thoughts can be the following:</p><ul><li>&ldquo;I am not smart/good enough.&rdquo;</li><li>&ldquo;I don&rsquo;t deserve this love.&rdquo;</li><li>&ldquo;I can never do this.&rdquo;</li><li>&ldquo;I&rsquo;ll never get lucky like them.&rdquo;</li><li>&ldquo;I am nothing but bad luck.&rdquo;</li></ul><p>&nbsp;</p><p>These simple practices can be done to somehow diminish your negative thinking.</p><p>&nbsp;</p><p>Know Your Triggers</p><p>Negative thoughts can take the form of anxiety, overthinking, lack of self-confidence, and low self-esteem. These usually result from bad experiences that have subjected you to shame, humiliation, and embarrassment. On the other hand, some people are just over stressed, hungry, and sleep-deprived. These can contribute to the way our minds think negatively</p><p>&nbsp;</p><p>Manage Stress And Anger</p><p>Proper stress and anger management will help you to think clearly and avoid letting emotions make decisions. It can also help you spot the problem and think of an answer to address it.</p><p>&nbsp;</p><p>Write About Your Feelings And Emotions</p><p>Your feelings and emotions about a particular thing or scenario are valid. Don&rsquo;t think of yourself as going crazy or just getting cranky. It may just be a phase but your negative thoughts won&rsquo;t pop out of nowhere without any reason. Jotting down these feelings and scenarios will help you identify your trigger.</p><p>&nbsp;</p><p>Join Support Groups</p><p>You&rsquo;ll find people in the same situation in forums and support groups. You are never alone in your problems. People in support groups will share about their experiences of shame, guilt, and embarrassment and narrate how they overcame it. You might find answers and insights on their own experiences.</p><p>&nbsp;</p><p>Final Thoughts</p><p>A complete sleep and quality breaks can also work to ease your negative thinking. However, some negative thoughts are brought by other reasons that cannot really be remedied by a full sleep. The self-care practices above can help you find your triggers and address them early before it gets worse.</p><p>&nbsp;</p>",
                'category' => "personal_development",
                'category_id' => 3
            ),
            array(
                'article_id' => '99999999921',
                'article_name' => 'Proven Tips To Have A Millionaire Mindset',
                'article_content' => "<p>Proven Tips To Have A Millionaire Mindset</p><p>&nbsp;</p><p>Establish Firm Goals</p><p>Focus on these goals and always go for it. When you have a clear bucket list and all the steps are properly planned to achieve it, then you are already halfway towards success. Rich people know that these goals cannot be achieved overnight, but small steps can be done in a shorter period. Once you have a firm goal, chances are high that you will do your best to avoid defeat.</p><p>&nbsp;</p><p>Invest Your Money</p><p>Rich people never relied wholly on their active jobs to generate money. They have passive income and large investments. These people started with small investments but they are not afraid to take risks. Believe it or not, it is the investments that would afford you the lifestyle that you want in the future.</p><p>&nbsp;</p><p>Be Teachable</p><p>Don&rsquo;t stop learning. Even the most successful billionaires hire experts and ask the help of other people to teach them about a topic they don&rsquo;t know about. Millionaires invest in themselves, too. They know that the most powerful weapon is education and they don&rsquo;t take this advice for granted.</p><p>&nbsp;</p><p>Now Is The Right Time</p><p>A millionaire mindset hates procrastination. Once an opportunity arrives, it is never to be let go or to be set aside for later. Millionaires and successful people know that time is of essence so better grab that chance now.</p><p>&nbsp;</p><p>Final Thoughts</p><p>A millionaire mindset always keeps in mind that the proper investment starts with yourself and your habits. There is no fixed formula to develop this kind of winning mindset but these practices are guaranteed to help you think like a millionaire!</p><p>&nbsp;</p>",
                'category' => "personal_development",
                'category_id' => 3
            ),
            array(
                'article_id' => '99999999922',
                'article_name' => 'How To Keep Marriage Strong After Baby',
                'article_content' => "<p>How To Keep Marriage Strong After Baby</p><p>&nbsp;</p><p>They say that children can make couples happier and stronger. However, real-life stories state the opposite. Most couples encounter rocks in their relationship after having a child. N order to keep your marriage strong even after having your first baby, consider the following tips:</p><p>&nbsp;</p><p>Check On One Another</p><p>&nbsp;</p><p>Communication is the key to a healthy relationship. Reconnect with each other like boyfriends and girlfriends do. Keep that spark alive between the two of you by checking on each other every now and then. Tell stories about your day-to-day activities by the end of the day.</p><p>&nbsp;</p><p>Share The Burden</p><p>&nbsp;</p><p>The workload of a parent is really heavy when it is not shared with the other. Motherhood can become physically tiring if it&rsquo;s only the mother who does all the work. Both the mother and the father should also share in the responsibilities of taking care of the baby. The duties should be well-communicated with each other.</p><p>&nbsp;</p><p>Go Out On A Date</p><p>&nbsp;</p><p>Your life as a romantic couple does not end just because you already have a baby. Find a babysitter (preferably other family members) so you two could go out and have fun like a young couple. Don&rsquo;t feel guilty that you are separating from your kid for just a moment. This trick will keep that spark alive and release any tension between the two of you.</p><p>&nbsp;</p><p>These tips will surely help you get that romantic feeling back in your relationship. Also, don&rsquo;t hesitate to reach out for help with other family members when things are already getting tough!</p>",
                'category' => "relationships_dating",
                'category_id' => 4
            ),
            array(
                'article_id' => '99999999923',
                'article_name' => 'Top 4 Effective Tips To Help You Move On From A Painful Breakup',
                'article_content' => "<p>Top 4 Effective Tips To Help You Move On From A Painful Breakup</p><p>&nbsp;</p><p>Everyone knows how painful the breakup is the day after the actual breakup.The day after is usually the day when everything sinks in - that you are no longer together and there&rsquo;s no more chance of both of you coming back together. As early as now, please accept the fact that you are really hurting and that it&rsquo;s okay to grieve. However, that grief should not stay with you forever. Below are the best practices to help you move on from a painful and sudden breakup from your ex-lover:</p><p>&nbsp;</p><p>Disconnect From Social Media</p><p>&nbsp;</p><p>Checking his or her social media account every now and then is a bad idea. It is really tempting to check how he or she is doing now that you are over but it&rsquo;s not doing you any good. Block their accounts if you must. Moreover, being on social media after a break up may make you envy those happy couples showing on your newsfeed.</p><p>&nbsp;</p><p>Pamper Yourself</p><p>&nbsp;</p><p>Let&rsquo;s talk about self-care. Your heart has been beaten to pieces after hearing or reading those parting words from your ex-lover. Don&rsquo;t do the same to yourself! You only have yourself now as of the moment. Don&rsquo;t deprive yourself of the proper nutrition and all the means to make you happy as of the moment. Indulge in your favorite food. Go online shopping. Spend more time with your pets and other family members.</p><p>&nbsp;</p><p>Talk About It With Friends</p><p>&nbsp;</p><p>Your friends will play a huge part to get you back on track afterthat breakup. Don&rsquo;t hesitate to reach out and tell them your story if you&rsquo;re comfortable doing so. More often than not, they will give you fresh perspective about life and relationships in general. They will make you laugh aat certain things and forget about your ex.</p><p>&nbsp;</p><p>Find A New Hobby</p><p>&nbsp;</p><p>Get busy so you are distracted from the pain this breakup caused you. Try new hobbies that you&rsquo;ve always wanted to do. When your mind is full of other things, chances are high that you&rsquo;d even forget you&rsquo;ve just been in a breakup.</p><p>&nbsp;</p><p>&nbsp;</p><p>Life continues even after you and your ex-lover parted ways. The world is full of possibilities to make you happy. So start these life hacks and get your life back from that hurtful relationship.</p>",
                'category' => "relationships_dating",
                'category_id' => 4
            ),
            array(
                'article_id' => '99999999924',
                'article_name' => 'Signs That You Are In A Toxic Relationship',
                'article_content' => "<p>Signs That You Are In A Toxic Relationship</p><p>&nbsp;</p><p>A toxic relationship is another kind of an unhealthy relationship. The challenges that a couple encounters along the way are healthy but these bumps should not lead to a toxic connection. If you&rsquo;ve been noticing that your current relationship is seemingly off nowadays, check these other warning signs that indicate that you might be in a toxic relationship today.</p><p>&nbsp;</p><p>Lack of Moral Support</p><p>&nbsp;</p><p>A healthy relationship involves you and your partner&rsquo;s desire to see each other&rsquo;s successes. Both of you will be there everytime either experiences a challenge or a problem on your personal endeavors. Moral encouragement and inspiring words should fill your daily conversations too, regularly if not everyday. However, if this has already become a race and competition between the two of you. Then it&rsquo;s a warning sign of a toxic relationship.</p><p>&nbsp;</p><p>One Of You Is Always Blaming The Other</p><p>Shifting blame to another is a sign of an unhealthy relationship. Even if one you is really at fault, the blaming game should not go any further. The damage has already been done and the best way to fix it is to work on it together, instead of finding faults on each other.</p><p>&nbsp;</p><p>Lack Of Proper Communication</p><p>Beware of the dismissive tendencies that you or your partner may be doing. A busy day should not shut down all forms of communication between the two of you. Also, watch out for forms of hostile communication such as yelling, throwing of things, name-calling, and hints of belittling that you may be hearing from your partner.</p><p>&nbsp;</p><p>Lots Of Comparisons</p><p>&nbsp;</p><p>Your partner should not be comparing you with other people and make it seem like they are better than you. Even if it&rsquo;s just a form of joke, a healthy relationship should not make you feel like you lack desirable traits.</p><p>&nbsp;</p><p>Lying A Lot</p><p>&nbsp;</p><p>If you caught your partner lying more than once, maybe it&rsquo;s time to reassess your relationship and his/her commitment to you. If your partner respects you, then he or she should not be lying in the first place. No matter how little this lie is, it can already question one&rsquo;s credibility so keep this in mind.</p>",
                'category' => "relationships_dating",
                'category_id' => 4
            ),
            array(
                'article_id' => '99999999925',
                'article_name' => 'What Is Family Counseling And Why Is It Important',
                'article_content' => "<p>What Is Family Counseling And Why Is It Important</p><p>&nbsp;</p><p><strong>Family Counseling, Defined</strong></p><p>Also called family therapy, family counseling is a treatment plan which includes sessions that teach family members about certain skills. The therapy session can be one-on-one or a group session, depending on the therapist&rsquo;s advice and the needs of the family undergoing the counseling.</p><p>&nbsp;</p><p>At first, the therapist will talk to the family about the objectives of the therapy to help them understand what&rsquo;s going to happen. Each member will be asked about how their problems started and the current situation of the family. The therapist will come up with a treatment plan which is best suited for the family.</p><p>&nbsp;</p><p><strong>The Importance Of Family Counseling</strong></p><p>Families who undergo this counseling aim to address underlying conflicts, communication issues, and relationship problems among them. The therapists do their best to facilitate open communication among the family members and to provide them fresh perspective after going to the root cause of the problem. They aim to resolve negative behaviors and patterns in the family, and, at the same time, see to it that each member develops emotional awareness towards one another.</p><p>&nbsp;</p><p><strong>Who May Avail This</strong></p><p>Families who undergo counseling are not always problematic families. Specific therapy sessions are available in the following scenario:</p><ul><li>a family member has an addiction/substance abuse problem</li><li>a family member has a mental illness and the other members are being counselled regarding the best strategies to help him/her cope up</li><li>a child is in conflict with the law and the parents are being counseled regarding the best possible way to rehabilitate the kid</li></ul><p>&nbsp;</p><p>Family members who are in need of medical assistance will continue their treatment while the other members are undergoing counseling sessions.</p><p>&nbsp;</p><p>Family counseling is important to restore good relationships among the family members and to restore them. to their harmonious environment. Don&rsquo;t hesitate to contact one in your local area to book an appointment and see what kind of therapy is good for you and the whole family.</p>",
                'category' => "relationships_dating",
                'category_id' => 4
            ),
            array(
                'article_id' => '99999999926',
                'article_name' => 'How To Keep Marriage Alive When It Gets Boring',
                'article_content' => "<p>How To Keep Marriage Alive When It Gets Boring</p><p>&nbsp;</p><p>If you feel like your marriage is getting boring after years of being married together. Most couples admit this fact, indeed. If you are looking for the most effective way to rekindle your relationship, this list is here for you.</p><p>&nbsp;</p><p>Plan Date Nights</p><p>No one can beat a romantic date night to bring back that spark in your relationship. If you have kids, hire a good babysitter to watch over them while you go on your date. Make it feel like you are on the honeymoon stage again.</p><p>&nbsp;</p><p>Try Adventures Together</p><p>Aside from dates, you can also go on trips together just like what you used to do when you were still boyfriends and girlfriends. Having a family does not mean that you had to let go of your spontaneous trips and adventures to give way to kids.</p><p>&nbsp;</p><p>You and your partner alone can also try going away for a weekend. Work stress and pressure can take a toll on each of your mental health, physique, and even put a strain on your relationship. Do this to refocus and refuel yourselves. Do this at least once a year to keep your marriage alive.</p><p>&nbsp;</p><p>Communicate Effectively</p><p>Communication should be a 2-way street. The other one listens when the other talks. Don&rsquo;t dismiss any problem or issue that your partner may become worried about. Conflicts usually arise because there is no effective communication between couples.</p><p>&nbsp;</p><p>Be Flirty</p><p>Remember those times when both of you are on the dating stage? Stop those boring talks and get intimate. Besides, it&rsquo;s a very good stress relief!</p><p>&nbsp;</p><p>Prepare Surprises</p><p>A simple coffee delivery to your husband&rsquo;s office can do this trick. Surprise your wife with a new dinner course you prepared just for her. Everyone loves surprises. Everyone loves to smile at random things sent to them by their loved ones.</p><p>&nbsp;</p><p>&nbsp;</p><p>Remember, love is still there. Your marriage is not broken. Your relationship has just become routinary. You just need to reignite that fire between the two of you to spice things up a little bit.</p>",
                'category' => "relationships_dating",
                'category_id' => 4
            ),
            array(
                'article_id' => '99999999927',
                'article_name' => 'What Does A Healthy Relationship Look Like',
                'article_content' => "<p>What Does A Healthy Relationship Look Like</p><p>&nbsp;</p><p>A healthy relationship is composed of a lot of things. Consider the following to assess whether or not you are in the right relationship today:</p><p>&nbsp;</p><p>There Is Respect On Both Parties</p><p>Your partner knows and respects your boundaries. He or she knows that you have your own personal space and there are times that you just want time for yourself. It is not selfish. If you are not fond of public displays of affections, then your partner should be okay with that. Anything that makes you uncomfortable should be avoided.</p><p>&nbsp;</p><p>Both Of You Are Openly Communicating With Each Other</p><p>Effective communication is the key to long-lasting relationships. Both you and your partner are open about your feelings. If one is angry, then he or she should tell what made it happen. If there is miscommunication, both parties are affected. This lack of effective communication can even lead to conflicts, exchange of hurtful words, and even a breakup.</p><p>&nbsp;</p><p>You Feel Secure</p><p>Your partner is not judging you on everything that you do. You can be yourself without fear that you would be judged. Both of you trust each other. Secrets that have been shared are not revealed to anyone. You know that your partner is reliable when he or she gets worried if you&rsquo;ve made it safely to your home.</p><p>&nbsp;</p><p>You Are Never Embarrassed Or Humiliated</p><p>A healthy relationship will not subject you to feelings of shame, guilt, and disappointment. Your partner will never humiliate you in front of people or belittle your skills to your common friends. A healthy relationship should make you feel proud of yourself.</p><p>&nbsp;</p><p>If these tips point out that you are in a healthy relationship, then congratulations, consider yourself lucky that you found someone who respects you and loves you for who you are. Be wary if your partner exhibits red flags (which are the opposite of this list), don&rsquo;t let your guard down just because you love this person.</p>",
                'category' => "relationships_dating",
                'category_id' => 4
            ),
            array(
                'article_id' => '99999999928',
                'article_name' => 'Warning Signs That My Partner Is Not Supportive',
                'article_content' => "<p>Warning Signs That My Partner Is Not Supportive</p><p>&nbsp;</p><p>A supportive partner will always be all-ears at your rants and worries. He or she will listen about how your day went and even the smallest details about your work. A healthy relationship should be composed of 2 people ready to support each other on their goals and small wins in life.</p><p>&nbsp;</p><p>Here are the top warning signs that you have an unsupportive partner:</p><p>&nbsp;</p><p><strong>They Neglect Your Feelings</strong></p><p>Usually, they would say that it&rsquo;s all in your head. An unsupportive partner will make it appear like it isn&rsquo;t really a big deal. They would avoid your drama until you get tired of it. Remember, your emotions are valid. You are upset at something because you have a reason to be. Your partner should at least hear you and listen about anything that&rsquo;s bugging you.</p><p>&nbsp;</p><p><strong>They Are Always Busy</strong></p><p>More often than not, an unsupportive partner will miss important celebrations in your life. Or worse, they won&rsquo;t show their festive self when you are celebrating your promotion, good grades, and small achievements. Their usual reason is that they are always busy. A good partner should know that you are not to be taken for granted and that you deserve quality time, too.</p><p>&nbsp;</p><p><strong>They Avoid Tough Conversations</strong></p><p>When you are talking about problems in your relationship, an unsupportive partner will oftentimes dismiss it. They would usually say that you could talk about it later until the issue dies completely.</p><p>&nbsp;</p><p><strong>They Show Lack Of Interest</strong></p><p>Lack of interest in your achievement is a red flag. Lack of interest about how your day went is also a red flag. Your partner should be someone who&rsquo;s all-ears when it comes to your rants. A partner who is not supportive would talk about his or her day instead and make it appear like they had a worse day than yours.</p>",
                'category' => "relationships_dating",
                'category_id' => 4
            ),
            array(
                'article_id' => '99999999923',
                'article_name' => 'What Is First Aid Training And Where Do I Get One?',
                'article_content' => "<p>What Is First Aid Training And Where Do I Get One?</p><p>&nbsp;</p><p>First aid training is defined as a set of courses aiming to educate students about the proper life-saving method initially done on an injured person. First aid trainings include lectures and actual demonstrations on how a particular method is done. The final goal of people who learn about this is to equip themselves with knowledge about immediate emergency care in all kinds of life-threatening situations</p><p>&nbsp;</p><p>Common Life-Threatening Situations</p><p>&nbsp;</p><p>Below are the most common situations that need immediate care for the safety and survival of the person injured</p><p>&nbsp;</p><p>Unconsciousness</p><p>First aid training will teach the most fundamental medical procedure&nbsp; - the cardiopulmonary resuscitation or known as the CPR. Cardiac arrest happens when the injured person is not anymore pumping blood. Without first aid administration, this person will die at that moment.</p><p>&nbsp;</p><p>There is a proper way to do CPR or else, it could break a person&rsquo;s rib and do more harm than good. First aid training students will have to perform CPR by themselves on a mannequin under the supervision of a trained specialist.</p><p>&nbsp;</p><p>Bleeding</p><p>It should be attended to immediately or it will result in death due to blood loss. The source and reason for the non-stop bleeding should be assessed. Even while the person injured is being transported, a medical aid should be with him to prevent much bleeding.</p><p>&nbsp;</p><p>Choking</p><p>This is most common to infants and kids when they ingested a small toy that blocks their airways. The most common sign of choking include gasping, gagging, and face turning blue. Proper first aid training is to put arms around their waist and do quick thrusting to make the person spit out whatever was obstructing their airways.</p><p>&nbsp;</p><p>Where Can I Learn About First Aid Training</p><p>&nbsp;</p><p>Ask your local government if they sponsor first aid training to students who want to enroll in one. Your local Department of Health may also have classes regarding this. Most schools also have their own first aid training curriculum that you can enroll in.</p>",
                'category' => "survival",
                'category_id' => 5
            ),
            array(
                'article_id' => '99999999924',
                'article_name' => 'Top 5 Basic Survival Skills',
                'article_content' => "<p>Top 5 Basic Survival Skills</p><p>&nbsp;</p><p>Basic survival training is more than just a subject in school. It&rsquo;s more than just an extracurricular project too. Emergency happens all the time and we cannot control what comes next once that day arrives. Here are the 5 basic survival skills everyone should master:</p><p>&nbsp;</p><p>Starting A Fire</p><p>Fire is important because it will keep you warm and safe from wild animal. It will also cook food for nourishment once you got yourself alone in the woods. Starting a fire seems easy when you watch movies and TV series about people doing the same, however, it needs a lot of work especially when your materials are damp.</p><p>&nbsp;</p><p>Self-Defense</p><p>Everyone has to learn at least one self-defense technique in his lifetime. The world is considered a dangerous place nowadays. You don&rsquo;t have to get into the woods to make use of this skill. Everywhere you go, there&rsquo;s always a chance that someone is out there wanting to harm you.</p><p>&nbsp;</p><p>First Aid</p><p>First aid is a must to prevent further damage and eventual death to the injured person. First aid techniques have already saved a lot of people on the brink of death. A simple gush of wound can kill you due to major loss of blood. A simple injury can aggravate if not given the proper first aid treatment.</p><p>&nbsp;</p><p>Building Shelter From Scratch</p><p>&nbsp;</p><p>If you happen to get lost in the middle of nowhere or in a forest, your way back home would take almost a day. Your physical self cannot withstand the elements of nature - mainly the rains, snow, cold temperature, fog, or even the heat in tropical climates. If building a temporary shelter from scratch is far from happening, then the best thing to do is to find a decent structure (a boulder or a tree) that could give you a temporary solace to pass the night.</p><p>&nbsp;</p><p>Making Your Own Safe Drinking Water</p><p>You can go on a day without food but not without water. Clean drinking water is vital for a person to function and be alive in a day. When you get lost into the woods, it&rsquo;s impossible that you&rsquo;ll find purified water in the middle of the jungle. It&rsquo;s up to you now how to purify water from the streams.</p><p>&nbsp;</p><p>These basic survival skills are the most important that you or your kids should learn. Whether or not you are going into the woods, these skills are vital even in the dangerous world that we live in nowadays.</p>",
                'category' => "survival",
                'category_id' => 5
            ),
            array(
                'article_id' => '99999999925',
                'article_name' => 'Fire Prevention And Safety Tips To Teach Your Family Members',
                'article_content' => "<p>Fire Prevention And Safety Tips To Teach Your Family Members</p><p>&nbsp;</p><p>There are a lot of fire hazards the can be found inside your home. It&rsquo;s not easy to spot one so better teach your family members what are the most commonly reported things and neglected activities that caused house fires and explosions throughout the years. Below are the tips that you can teach your kids to avoid any untoward fire accidents.</p><p>&nbsp;</p><p>Unplug Electrical Appliances When Not In Use</p><p>Substandard appliances are the usual cause of fire. Short circuits can happen anytime. Even without human intervention, faulty wiring and production of these home appliances present a fire hazard that could compromise your safety and your investments.</p><p>&nbsp;</p><p>Don&rsquo;t Leave Cooking Unattended</p><p>Fire accidents happen because people forgets about their cooking while they answer the phone, go to shower, or even check their social media. It would already be too late because smoke won;t get noticed unless a large portion of the kitchen have already been gutted by fire. Check combustibles too near the heat source. Don&rsquo;t put potholders and rags near the stove.</p><p>&nbsp;</p><p>Install Smoke Alarms</p><p>Smoke detection alarms can save your life and the whole house from being turned into ashes. Alarms can warn you even the tiniest hint of an impending fire.</p><p>&nbsp;</p><p>Keep Emergency Hotlines In Your Phone</p><p>Make sure that help is within your reach always. Most households also post emergency numbers on conspicuous places at home so each member will know who to call once a certain emergency arises.</p><p>&nbsp;</p><p>Keep Out Flammable Hazards Out Of The Reach Of Children And Pets</p><p>Flammable materials should only be for the use of adults. Kids are experimental and their curiosity can put down the whole house. Keep these flammable hazards in a well-ventilated room out of the reach of your kids and pets.</p>",
                'category' => "survival",
                'category_id' => 5
            ),
            array(
                'article_id' => '99999999926',
                'article_name' => '5 Reasons Why A Camping Trip Is A Must In This Lifetime',
                'article_content' => "<p>5 Reasons Why A Camping Trip Is A Must In This Lifetime</p><p>You might be wondering why people are obsessed with camping and do this activity with friends at least once a year. They have their reasons to do so, aside from adventure. You too should also endeavor to go camping at least once a year for the following reasons:</p><p>&nbsp;</p><p>It Can Teach You About Life Skills</p><p>The world is a dangerous place. You can hone your survival skills. Treat camping and the woods as your teacher when it comes to living in the harsh realities of the world.</p><p>&nbsp;</p><p>You Can Explore Nature Freely</p><p>People go camping to stay away from city life and the digital world. Most of them find happiness and clarity with nature. People go for digital detox to take a break from the stress brought about by technology. A simple weekend break at home won&rsquo;t really remedy this type of stress. Camping to a safe and secluded place will do this trick instead.</p><p>&nbsp;</p><p>Camping Can Improve Your Overall Well-Being</p><p>Campers are able to breathe fresh air when they go camping. This is the healthiest escape from the pollution in the city. Campers also find mind clarity and they claim that being with nature calms their emotions. After a 3-day camp, people usually go back to their normal lives feeling refreshed and more productive.</p><p>&nbsp;</p><p>It Can Strengthen Relationships</p><p>Of course, you won&rsquo;t go camping alone by yourself. If you&rsquo;re not going with friends or family, you&rsquo;ll still meet people along the way. Camping sites are always flocked with people finding comfort and adventure with nature. You&rsquo;ll be surprised how effective face-to-face communication still is. In fact, it delivers the message better than technological conversations.</p>",
                'category' => "survival",
                'category_id' => 5
            ),
            array(
                'article_id' => '99999999927',
                'article_name' => 'Emergency Tools You Need To Keep Inside Your Home',
                'article_content' => "<p>Emergency Tools You Need To Keep Inside Your Home</p><p>&nbsp;</p><p>An emergency kit or two need to be stored in conspicuous places in the house in case an emergency arises. Common emergencies at home include fire and earthquakes. A bag full of emergency tools should be easy to carry by any member of the family. The following tools are a must:</p><p>&nbsp;</p><p>Medicines</p><p>Medications such as pain relievers should be stored in a pill box in your emergency bag. Prepare anti-diarrhea medicines, antihistamines, and personal medication as well. These are very handy in case you got stuck inside your home. Antiseptic medicines such as aloe vera gel should also be included. Make sure that none of you and your family are allergic to these medications, otherwise, jot it down in a notepad. As a reminder, don&rsquo;t give aspirin to kids. Aspirins are suitable for adults experiencing chest pains.</p><p>&nbsp;</p><p>Flashlight</p><p>In case of power outages, everyone is at risk of falling and stepping on broken glasses while in a state of panic. Provide mini flashlights and batteries in your emergency bags.</p><p>&nbsp;</p><p>Clean Drinking Water and Food</p><p>In cases of flood, tornado, or earthquake and you got stuck in your house, the water running in your sink is possibly not safe for drinking. A 3-day supply of clean drinking water (bottled water preferably) and food shall be stored inside the house. Keep in mind not to stock up on foods that are high in salt as it can increase thirst.</p><p>&nbsp;</p><p>First Aid Kit</p><p>Injuries are possible during calamities and natural disasters. You can purchase first aid kits containing gauze, soap, bandages, sterile gloves, ointment, and scissors - all enough to treat life-threatening wounds.</p><p>&nbsp;</p><p>Pocket Knife</p><p>A survival knife has many uses in times of emergency. You can use it to open food packets, as a weapon in self-defense, to adjust clothing for comfort and safety, and as a hammering tool on appropriate purposes.</p><p>&nbsp;</p><p>Emergency Hotlines And A Cellular Phone</p><p>Communication is a must during disasters. Gather all the hotline numbers of the government agencies in charge of rescue operations in your local area and keep a fully-charged emergency phone in your kit.</p><p>&nbsp;</p><p>Final Reminder</p><p>Your family should know the basic first aid in case someone needs it during a disaster. Tell about these emergency kits and tools to your family so they&rsquo;d know how to use them and where to find them in case of emergencies.</p>",
                'category' => "survival",
                'category_id' => 5
            ),
            array(
                'article_id' => '99999999928',
                'article_name' => 'Most Common Household Emergencies',
                'article_content' => "<p>Most Common Household Emergencies</p><p>&nbsp;</p><p>Household emergencies happen all the time. In fact, it happens when we least expect it. It cannot really be avoided, no matter how careful we are in our day-to-day lives. However, immediate remedies are also available for these emergencies. Let&rsquo;s tackle the three most common.</p><p>&nbsp;</p><p>Power Outages</p><p>Most power outages are beyond the control of the homeowners. Especially during disasters, electricity wont come back immediately after the main reason is fixed by the provider. Make sure that you have flashlights and power banks ready to power your phones for proper communication. A non-electric stove is also useful so you can still cook food if the outage lasts for a day or so. Battery-powered fans and a fireplace can protect you against harsh temperatures while your electricity flow is being fixed.</p><p>&nbsp;</p><p>Broken Heating System</p><p>it&rsquo;s either that your heating system will not turn off or cool air is coming out instead. A system that won&rsquo;t turn off can be remedied by setting the system into &ldquo;auto&rdquo; instead of &ldquo;on&rdquo;. It could also be because of a broken thermostat. Check the manual first before contacting a repair specialist to see if you can do the repair by yourself.</p><p>&nbsp;</p><p>Water Leak</p><p>Water leak happens because of broken or worn out valve. The best thing to do when you have this emergency is to locate the main valve in the house and turn it off. Immediately call a plumber to help you fix whatever is causing the water leak.</p><p>&nbsp;</p><p>If it is the ceiling leaking, better have those pails and buckets under the leak. Ask the help of a professional right away because the damage itself, if not treated, can do more harm to your house.</p><p>&nbsp;</p><p>Broken Window</p><p>A broken window needs to be repaired immediately for security purposes. Assess the damage and prepare the necessary materials to fix it temporarily. If there are large cracks, duct tape will be helpful. If the cracks are small, a glue or nail polish0 will do.</p>",
                'category' => "survival",
                'category_id' => 5
            ),
            array(
                'article_id' => '99999999929',
                'article_name' => 'Self-Defense Tips Every Woman Should Know',
                'article_content' => "<p>Self-Defense Tips Every Woman Should Know</p><p>&nbsp;</p><p>Women are the most easy targets of thieves and syndicates. Knowing the proper techniques to defend oneself is the best way to get out of the situation. For women out there reading this, remember that it&rsquo;s not always the case where you are with a friend or a protector anywhere you go. So, here are the best self-defense tips women of all ages should know to protect themselves from these perpetrators:</p><p>&nbsp;</p><p>Avoid Hitting The Chest And Knees</p><p>Aiming for the chest is ineffective. If you want to aim the knees, you should be able to use that specific kick or else it would be too risky. Use all your force towards the enemy&rsquo;s groin, nose, eyes, and throat. These are their vulnerable areas.</p><p>&nbsp;</p><p>Use All Your Force</p><p>You are a powerful woman. If you have to shout for help, then shout at the top of your lungs. Take a deep breath and don&rsquo;t think of the worst. Clench your fist tighter and properly. You can get out of this situation sooner if you&rsquo;ll use all your force to execute your attacks.</p><p>&nbsp;</p><p>Don&rsquo;t Let Your Guard Down</p><p>Once the attacker invades your personal space, it&rsquo;s time to be more alert and call for help immediately. Don&rsquo;t let your guard down this time, because the attacker is just looking for that perfect opportunity to bring you down. If you&rsquo;ve already noticed someone has been following you, don&rsquo;t let yourself wander from a lot of people.</p><p>&nbsp;</p><p>Let A Friend Know Where You Are.</p><p>Tell your best friend your usual route and routine after work/school. If you are going on a blind date, make sure that at least one of your friends knows where you are heading. Better yet, install security apps that will inform your friend and family members about your location once you send a distress help.</p><p>&nbsp;</p><p>Your Self-Defense Weapons Should Always Be With You</p><p>Pepper sprays are there to help you at times like this. Have the courage to pull it from your bag and aim towards the perpetrator. A swiss knife can also be handy, especially if you usually go home late at night.</p><p>&nbsp;</p><p>Learn About The Basic Self-Defenses</p><p>If you&rsquo;ve been grabbed by the hair, you can regain control by grabbing the perpetrators hands and run once he loses his grip. If you&rsquo;ve been grabbed by the hand, remember to twist your hand toward the perpetrator&rsquo;s thumb in a quick jerk.</p><p>&nbsp;</p><p>Remember not to put a lot of trust in people these days. Aside from surprise attacks, a perpetrator would usually gain your trust first before executing his dirty plans.</p>",
                'category' => "survival",
                'category_id' => 5
            )
        );
        $json = json_encode($articles);

        header('Content-Type: application/json; charset=utf-8');
//        echo json_encode($json);
        echo $json;
    }

    public function searchJson(){
        header('Content-Type: application/json; charset=utf-8');
        $json_url_dfy = "https://pushbutton-vip.com/DFYSitesContents/";
        $json_dfy = file_get_contents($json_url_dfy);
        $data_dfy = json_decode($json_dfy,1);

        $categoryID = '2';

        $expected = array_values(array_filter($data_dfy, function ($var) use ($categoryID) {
            $arrayList = ($var['category_id'] == $categoryID);
            return $arrayList;
        }));
        print_r($expected);
    }

    public function listCategory(){
        header('Content-Type: application/json; charset=utf-8');
        $json_url_dfy = "https://articles.thriivetank.com/api/categories";
        $json_dfy = file_get_contents($json_url_dfy);
        $data_dfy = json_decode($json_dfy,1);
        print_r($data_dfy);
    }

    public function searchFeed(){
        header('Content-Type: application/json; charset=utf-8');
        $url = basename($_SERVER['REQUEST_URI']);
        $json_url_dfy = "https://articles.thriivetank.com/feed/$url";
        $json_dfy = file_get_contents($json_url_dfy);
        print_r($json_dfy);
    }

    public function getByKeywords(){
        header('Content-Type: application/json; charset=utf-8');
        $json_url_dfy = "https://articles.thriivetank.com/api/keywords";
        $data['category'] = $_POST['category'];
        $data['keywords']  = $_POST['keywords'];
        $data['limit'] = $_POST['limit'];
        $data['offset'] = $_POST['offset'];
        $data['logic'] = $_POST['logic'];
		// print_r($_POST);
		// die();
//        print_r($_POST);
        $postdata = http_build_query($data);
        $opts = array('http' =>
            array(
                'method'  => 'POST',
                'header'  => 'Content-Type: application/x-www-form-urlencoded',
                'content' => $postdata
            )
        );

        $context  = stream_context_create($opts);
        $json_dfy = file_get_contents($json_url_dfy, false,  $context );
        //print_r($json_dfy);
//        var_dump($http_response_header->array[1]);
        $data_dfy = json_decode($json_dfy,1);
        if(count($data_dfy) <= 0){
            header('Content-Type: application/json; charset=utf-8');
            $json_url_dfy = "https://articles.thriivetank.com/feed/".$data['category'];
            $json_dfy = file_get_contents($json_url_dfy);
            print_r($json_dfy);
        }else{
            header('Content-Type: application/json; charset=utf-8');
            $json_dfy = json_encode($data_dfy);
            print_r($json_dfy);
        }
    }
}
?>